all:
	#g++ -c a.cpp
	#g++ -c b.cpp
	#g++ -c c.cpp
	#g++ c.o a.o b.o main.cpp
	#g++ b.o a.o c.o main.cpp
	#g++ -std=c++11 b.cpp c.cpp a.cpp main.cpp
	g++ -std=c++11 main.cpp a.cpp b.cpp c.cpp 
	#g++ -std=c++11 a.cpp c.cpp b.cpp main.cpp
